name: Testing
on:
  push:
    branches:
      - DEPRECATED
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          pip install --no-cache-dir --upgrade setuptools>=77.0 
          pip install numpy Cython scipy optuna scikit-learn
          pip install -r tests/requirements.txt
      - name: Install pymoo (DEBUG)
        run: |
          python setup.py install
      - name: Install pymoo
        run: |
          pip install .
          rm -rf pymoo
      - name: Check Compilation
        run: |
          python -c "from pymoo.functions import is_compiled;print('Compiled Extensions: ', is_compiled())"
      - name: Run Tests
        run: |
          pytest -v --no-header -m "not long"
